// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PersonnelManagementContext))]
    partial class PersonnelManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("GroupDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GroupDepartmentId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Department of Human Resources Management"
                        },
                        new
                        {
                            Id = 2,
                            GroupDepartmentId = 1,
                            Name = "Talent Planning, Acquisition and Development Division"
                        },
                        new
                        {
                            Id = 3,
                            GroupDepartmentId = 1,
                            Name = "Employee Service, Reletions and Policies Division"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Department of Finance"
                        },
                        new
                        {
                            Id = 5,
                            GroupDepartmentId = 4,
                            Name = "Budget Services Division"
                        },
                        new
                        {
                            Id = 6,
                            GroupDepartmentId = 4,
                            Name = "Accounts, Payments and Treasury Division"
                        },
                        new
                        {
                            Id = 7,
                            GroupDepartmentId = 4,
                            Name = "Financial Management of Technical Cooperation Division"
                        });
                });

            modelBuilder.Entity("Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1963, 9, 21, 11, 56, 48, 979, DateTimeKind.Local).AddTicks(7685),
                            FirstName = "Brown",
                            LastName = "Yundt"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1993, 5, 13, 11, 56, 48, 979, DateTimeKind.Local).AddTicks(7705),
                            FirstName = "Alvina",
                            LastName = "Schuppe"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1978, 3, 26, 11, 56, 48, 979, DateTimeKind.Local).AddTicks(7706),
                            FirstName = "Jaeden",
                            LastName = "Okuneva"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1966, 2, 5, 11, 56, 48, 979, DateTimeKind.Local).AddTicks(7707),
                            FirstName = "Deangelo",
                            LastName = "Bauch"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1992, 10, 12, 11, 56, 48, 979, DateTimeKind.Local).AddTicks(7709),
                            FirstName = "Davonte",
                            LastName = "White"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1993, 7, 14, 11, 56, 48, 979, DateTimeKind.Local).AddTicks(7710),
                            FirstName = "Joy",
                            LastName = "Buckridge"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1972, 4, 4, 11, 56, 48, 979, DateTimeKind.Local).AddTicks(7711),
                            FirstName = "Madyson",
                            LastName = "D'Amore"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1988, 8, 19, 11, 56, 48, 979, DateTimeKind.Local).AddTicks(7711),
                            FirstName = "Ibrahim",
                            LastName = "Rosenbaum"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1966, 6, 30, 11, 56, 48, 979, DateTimeKind.Local).AddTicks(7712),
                            FirstName = "Dessie",
                            LastName = "McGlynn"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1977, 10, 21, 11, 56, 48, 979, DateTimeKind.Local).AddTicks(7713),
                            FirstName = "Laisha",
                            LastName = "Glover"
                        });
                });

            modelBuilder.Entity("Model.PersonnelMovements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PersonnelMovements");
                });

            modelBuilder.Entity("Model.Department", b =>
                {
                    b.HasOne("Model.Department", "GroupDepartment")
                        .WithMany()
                        .HasForeignKey("GroupDepartmentId");

                    b.Navigation("GroupDepartment");
                });

            modelBuilder.Entity("Model.PersonnelMovements", b =>
                {
                    b.HasOne("Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
